# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171009_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_source',
            field=models.CharField(blank=True, choices=[(b'FACEBOOK', b'facebook'), (b'GOOGLE_PLUS', b'google-plus'), (b'SELF_SERVICE', b'self_service')], max_length=20, null=True),
        ),
    ]
